# Generated by Django 5.2 on 2025-04-08 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(default=None, max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("date_borrowed", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Av", "Available"),
                            ("Re", "Returned"),
                            ("Br", "Borrowed"),
                            ("Ov", "Overdue"),
                        ],
                        default="Av",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
