# Generated by Django 5.2 on 2025-10-06 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "group_name",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "description",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("city", models.CharField(default=None, max_length=20, null=True)),
                (
                    "time_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "active"), ("I", "inactive"), ("D", "Dead")],
                        default="A",
                        max_length=3,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("date_borrowed", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Requested", "Requested"),
                            ("Borrowed", "Borrowed"),
                            ("Overdue", "Overdue"),
                            ("Returned", "Returned"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
