# Generated by Django 5.2 on 2025-04-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("Av", "Available"),
                    ("Re", "Requested"),
                    ("Br", "Borrowed"),
                    ("Ov", "Overdue"),
                    ("R", "Returned"),
                ],
                default="Av",
            ),
        ),
    ]
