# Generated by Django 5.2 on 2025-04-15 11:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0002_alter_item_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(default=None, max_length=50)),
                ("description", models.CharField(default=None, max_length=200)),
                ("city", models.CharField(default=None, max_length=20)),
                (
                    "time_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 4, 15, 11, 6, 53, 507267, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "active"), ("I", "inactive"), ("D", "Dead")],
                        default="A",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
