# Generated by Django 5.2 on 2025-05-07 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0003_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="time_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 7, 20, 13, 42, 237125, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
