# Generated by Django 5.2 on 2025-09-11 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0004_alter_group_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="time_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 11, 11, 11, 17, 138522, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Requested", "Requested"),
                    ("Borrowed", "Borrowed"),
                    ("Overdue", "Overdue"),
                    ("Returned", "Returned"),
                ],
                default="Available",
            ),
        ),
    ]
