# Generated by Django 5.2 on 2025-09-11 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0005_alter_group_time_created_alter_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="time_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 11, 11, 33, 5, 44288, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(max_length=50),
        ),
    ]
