# Generated by Django 5.2 on 2025-09-11 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0006_alter_group_time_created_alter_item_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="time_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 11, 11, 45, 58, 976101, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
