# Generated by Django 5.2 on 2025-10-06 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0007_alter_group_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="city",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_name",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[("A", "active"), ("I", "inactive"), ("D", "Dead")],
                default="A",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="time_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Requested", "Requested"),
                    ("Borrowed", "Borrowed"),
                    ("Overdue", "Overdue"),
                    ("Returned", "Returned"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
